### ISSUE TITLE
执行命令有时候有输出，有时候没有

### ISSUE THREAD

**Issue by zhangchunlin** [chenquan/diskusage#50]
使用 go v1.18.6编译，环境：ubuntu 20.04
不输出的目录还没摸清楚规律，就是没有任何输出就结束了。

**Comment by chenquan** [comment]
能提供一下截图吗?
Can you give me a screenshot?

**Comment by zhangchunlin** [comment]
![image](https://user-images.githubusercontent.com/359281/189291092-50370305-34ee-4751-a22e-80cdcd41eacd.png)

**Comment by zhangchunlin** [comment]
感觉多跑几次就出来了，而且以后就都能打印出来数据了，是有更新数据库吗？一次超时没跑完就退出，多跑几次更新全了数据库就能打印了？

**Comment by chenquan** [comment]
![image](https://user-images.githubusercontent.com/20548053/189296298-13f3ef91-1ede-4cd8-84cf-ba31092e1368.png)

我在centos中测试不存在这个问题,你能帮助我提个PR修复这个问题吗?
I test in the centos does not exist the problem, can you help me make a PR to repair this problem?

**Comment by chenquan** [comment]
> 感觉多跑几次就出来了，而且以后就都能打印出来数据了，是有更新数据库吗？一次超时没跑完就退出，多跑几次更新全了数据库就能打印了？

不存在数据库被更新
There is no database is updated.

**Comment by zhangchunlin** [comment]
> 

我感觉没有显示的目录是那种文件和目录数量很多的。
另外我没做过go代码开发，可能要摸索学习比较久。有空试试查一下原因先。

**Comment by zhangchunlin** [comment]
我刚才找了另外一台ubuntu，测试的时候发现有一种情况也不打印，就是当前目录下有没有访问权限目录或者的时候，直接退出，没有任何报错。
当然这和我上面碰到的情况应该不一样。
我看代码里碰到错误都没有打印任何信息就退出了，应该在所有异常情况下都打印一下具体信息。

**Comment by zhangchunlin** [comment]
好像和没权限访问没关系，因为我切换成root用户跑，一样会出现这个问题。
我在 https://github.com/chenquan/diskusage/blob/master/internal/stat.go#L137 和 https://github.com/chenquan/diskusage/blob/master/internal/stat.go#L150 前后加了log，前面的log打印了，但是后面的log没打印，中间直接退出了，是panic了吗？我对go不熟悉不知道怎么跟下去了。

**Comment by chenquan** [comment]
You can use goland to debug
可以使用goland进行debug

**Comment by zhangchunlin** [comment]
我现在能重现问题的是一台server版的ubuntu，我也不会用golang，我用的是vscode
我现在是这样加的log，这行有打印：println("finish stating")
但是后面这行没有打印：println("finish stating")，中间的代码应该是遍历文件夹的，我看不懂，你看看有什么建议。
```
	go func() {
		defer close(errChan)

		println("begin to stat")
		files, err := find(dir, func(info fs.FileInfo) bool {
			if info.IsDir() {
				return true
			}

			name := info.Name()
			ext := filepath.Ext(name)
			_, ok := typeMap[ext]
			typeB := ok || len(types) == 0

			filterB := regexpFilter(name)

			return typeB && filterB
		})
		println("finish stating")
		if err != nil {
			println("find", err)
			errChan <- err
			return
		}
		println("get totalSize")
		totalSize := int64(0)
		for _, f := range files {
			totalSize += f.size
		}

		println("begin to print")
		val, reduceUnit := getReduce(unit, totalSize)
		header := fmt.Sprintf("Total: %0.3f%s\t%s", val, reduceUnit, color.HiGreenString(dir))
		colorPrintln(header)
		colorPrintln(strings.Repeat("-", len(header)+2))

		l := list.NewWriter()
		l.SetStyle(list.StyleConnectedLight)

		markPrint(files, limit, all)
		infoFiles := buildInfoFile(l, files, 0, depth, unit, totalSize)
		maxLen := 0
		for _, info := range infoFiles {
			if maxLen < info.strLen {
				maxLen = info.strLen
			}
		}
		printTree(l.Render(), infoFiles, maxLen)

		errChan <- nil
	}()
```

**Comment by chenquan** [comment]
> 我现在能重现问题的是一台server版的ubuntu，我也不会用goland，我用的是vscode 我现在是这样加的log，这行有打印：println("finish stating") 但是后面这行没有打印：println("finish stating")，中间的代码应该是遍历文件夹的，我看不懂，你看看有什么建议。
> 
> ```
> 	go func() {
> 		defer close(errChan)
> 
> 		println("begin to stat")
> 		files, err := find(dir, func(info fs.FileInfo) bool {
> 			if info.IsDir() {
> 				return true
> 			}
> 
> 			name := info.Name()
> 			ext := filepath.Ext(name)
> 			_, ok := typeMap[ext]
> 			typeB := ok || len(types) == 0
> 
> 			filterB := regexpFilter(name)
> 
> 			return typeB && filterB
> 		})
> 		println("finish stating")
> 		if err != nil {
> 			println("find", err)
> 			errChan <- err
> 			return
> 		}
> 		println("get totalSize")
> 		totalSize := int64(0)
> 		for _, f := range files {
> 			totalSize += f.size
> 		}
> 
> 		println("begin to print")
> 		val, reduceUnit := getReduce(unit, totalSize)
> 		header := fmt.Sprintf("Total: %0.3f%s\t%s", val, reduceUnit, color.HiGreenString(dir))
> 		colorPrintln(header)
> 		colorPrintln(strings.Repeat("-", len(header)+2))
> 
> 		l := list.NewWriter()
> 		l.SetStyle(list.StyleConnectedLight)
> 
> 		markPrint(files, limit, all)
> 		infoFiles := buildInfoFile(l, files, 0, depth, unit, totalSize)
> 		maxLen := 0
> 		for _, info := range infoFiles {
> 			if maxLen < info.strLen {
> 				maxLen = info.strLen
> 			}
> 		}
> 		printTree(l.Render(), infoFiles, maxLen)
> 
> 		errChan <- nil
> 	}()
> ```
哈喽，将`println`换成`fmt.println`,再尝试一下呢？
 hello, replace `println` with `fmt.println` and try again？

**Comment by chenquan** [comment]
我周末看一下

**Comment by zhangchunlin** [comment]
```
$ go build
# github.com/chenquan/diskusage/internal
internal/stat.go:148:7: undefined: fmt.println
```

**Comment by chenquan** [comment]
@zhangchunlin Hi,you take a look at this PR #52 , modify the problem?

**Comment by chenquan** [comment]
Hey, does the latest version solve your problem?

**Comment by zhangchunlin** [comment]
Yes, fixed no output issue, but still got error and exit, I will submit another issue.
