### ISSUE TITLE
Error: too many open files

### ISSUE THREAD

**Issue by zhangchunlin** [chenquan/diskusage#54]
Got error:
`Error: open /xxx/xxx/xxx.git/info: too many open files`
and exit.

After I use
`diskusage -w 100`
It became OK.

For the default worker number maybe too many, normal linux open files limit is 1024, so I suggest to reduce the default value to 512.

**Comment by chenquan** [comment]
good suggest! I'll finish it.

**Comment by zhangchunlin** [comment]
And I don't think too many workers will improve the performance, because the disk IO don't like CPU having so much cores, so maybe less worker number is enough, for example: 32
Some of my test data for a Total: 1672140.237M directory:

- 128: 0m12.967s
- 64: 0m9.898s
- 32: 0m7.520s
- 16: 0m14.583s
- 8: 0m16.081s

**Comment by chenquan** [comment]
> And I don't think too many workers will improve the performance, because the disk IO don't like CPU having so much cores, so maybe less worker number is enough, for example: 32 Some of my test data for a Total: 1672140.237M directory:
> 
> * 128: 0m12.967s
> * 64: 0m9.898s
> * 32: 0m7.520s
> * 16: 0m14.583s
> * 8: 0m16.081s

let me research again.
