### ISSUE TITLE
Minor feature requests

### ISSUE THREAD

**Issue by mshedsilegx** [chenquan/diskusage#72]
Hello,
Thank you for the helpful tool. Some features I think would be of interest:
1- Automatically calculate directory depth, for recursively traversing all sub folders, so we do not have to hardcode --depth
2- An option to only display directories, not files (--filter directories)
3- The separator is not displaying correctly for me on RHEL8. It is showing ââ instead of |
Changing the terminal emulation (xterm, linux) or LANG (en_US, en_US.UTF8) has no effect

```
Total: 14458.301M       /usr
---------------------------------
 4102.6M  28.4% ââ lib64
 3525.1M  24.4% ââ lib
 2355.1M  16.3% ââ share
 1925.1M  13.3% ââ bin
 1427.4M   9.9% ââ local
  441.3M   3.1% ââ libexec
  351.9M   2.4% ââ include
  188.7M   1.3% ââ sbin
  140.1M   1.0% ââ x86_64-w64-mingw32
    1.0M   0.0% ââ src
   10.0B   0.0% ââ tmp
   10.0B   0.0% ââ etc
```

**Comment by chenquan** [comment]
Thank you for your issue, I will follow up them.

**Comment by chenquan** [comment]
On the third point, can you help me to make a PR to solve? I don't have related equipment.

**Comment by chenquan** [comment]
> On the third point, can you help me to make a PR to solve? I don't have related equipment.

@mshedsilegx

**Comment by mshedsilegx** [comment]
Thank you for the response. You were right, the character issue was due to the terminal emulation that was not configured to render correctly UTF8 characters, not to the code at all. All good !
